import { MetadataRoute } from 'next'

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    { url: 'https://www.lexalytic.com', lastModified: new Date(), changeFrequency: 'monthly', priority: 1 },
    { url: 'https://www.lexalytic.com/services/power-bi', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/services/data-cleansing', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/services/excel-automation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/services/vba-development', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/services/power-automate', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/services/python-automation', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/services/google-sheets', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.9 },
    { url: 'https://www.lexalytic.com/about', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.7 },
    { url: 'https://www.lexalytic.com/blog', lastModified: new Date(), changeFrequency: 'weekly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/power-bi-consultant-cost-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/how-to-automate-excel-reports', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/power-bi-vs-excel', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/kpi-dashboard-small-business-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/late-payments-uk-business-data-fix', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/finance-team-manual-reporting-fix', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/sage-vs-xero-automated-reporting', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/connect-xero-to-excel-automate-reports', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/when-your-business-has-outgrown-excel', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/how-to-reduce-manual-data-entry-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/what-is-data-cleansing-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/excel-automation-cost-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/5-signs-manual-reporting-is-costing-your-business', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/automate-month-end-reporting-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/how-to-tell-if-your-business-is-profitable', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/staff-costs-eating-profit-how-to-track', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/how-to-see-which-jobs-clients-are-profitable', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/cash-flow-vs-profit-how-to-track-both', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/automate-invoice-tracking-excel-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/stop-business-running-on-gut-feeling', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/excel-reporting-recruitment-agencies-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/reduce-admin-time-small-business-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/power-bi-small-business-uk-worth-it', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/accountant-asking-for-spreadsheets-how-to-fix', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/sales-pipeline-dashboard-power-bi-excel', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/live-reports-from-xero-sage-quickbooks', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/automate-payroll-reporting-excel-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/how-to-track-project-profitability-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/data-automation-professional-services-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/reduce-month-end-stress-finance-team-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/prepare-business-data-self-assessment-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/true-labour-cost-per-employee-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/what-is-making-tax-digital-uk-business', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/excel-vs-accounting-software-what-lives-where', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/automate-vat-return-preparation-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/budget-vs-actuals-report-automated-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/year-end-reporting-uk-small-business', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/close-year-end-accounts-without-panic-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/set-up-business-reporting-new-year-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/business-performance-at-a-glance-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/automate-weekly-management-report-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/what-data-does-your-business-need-to-grow-2027', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/year-end-data-checklist-uk-small-business', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/start-new-year-clean-business-data-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/fix-business-reporting-before-january-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/make-business-run-itself-while-you-take-a-break', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/2027-business-data-resolution-how-to-keep-it', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/one-report-every-uk-business-owner-needs-january', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
    { url: 'https://www.lexalytic.com/blog/excel-automation-construction-companies-uk', lastModified: new Date(), changeFrequency: 'monthly', priority: 0.8 },
  ]
}
